name: Custom Applications CI

on: [push]

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: yarn install --pure-lockfile
      - name: Test
        run: yarn run test
      - name: Lint
        run: yarn run lint
      - name: Build
        run: yarn run build
        env:
          CLOUD_IDENTIFIER: ${{ vars.CLOUD_IDENTIFIER }}
          APPLICATION_ID: ${{ vars.APPLICATION_ID }}
          APPLICATION_URL: ${{ vars.APPLICATION_URL }}
          INITIAL_PROJECT_KEY: ${{ vars.INITIAL_PROJECT_KEY }}
          LOGO_MUST_BE_VISIBLE: ${{ vars.LOGO_MUST_BE_VISIBLE }}